--- 
title: "Models on the Peer Models Network"
author: "Amin Adibi, Stephanie Harvard, Mohsen Sadatsafavi"
date: "`r Sys.Date()`"
site: bookdown::bookdown_site
documentclass: book
biblio-style: apalike
link-citations: yes
description: "User guide for accessing models hosted on the Peer Models Network cloud."
---

# Introduction


[Peer Models Network](https://www.peermodelsnetwork.com/) is an initiative to make models for healthcare decision-making accessible, transparent and interpretable to all British Columbians. With support from the Canada Foundation for Innovation, BC SUPPORT Unit and BC Academic Health Science Network, the Peer Models Network (PMN) aims to increase engagement between the modelling community and policymakers, interdisciplinary scholars, patients, journalists, and other members of the public.

The PMN centres around a software infrastructure called the Programmable Interface for Statistical and Simulation Models (PRISM). PRISM hosts models on the cloud and provides standard Application Programming Interfaces (APIs) that allows users of different levels of technical backgrounds to interact with models hosted on a cloud. Users can submit queries to cloud-hosted models through a multitude of software platforms, including Microsoft Excel, R, Python, bash scripts, Javascript and custom web apps. This enables direct access to users who lack either the software or hardware infrastructure or the technical expertise to set up models on their own devices. It also enables more technical users to integrate modes with other pieces of softwar

In its current implementation, PRISM can hosts models that are developed in R, including those that use `Cpp` and `STAN`. 

Synchronous APIs calls are currently implemented and support for asynchronous calls that are required by extra long processing times is under active development. 
